#!/usr/bin/env node
// Pull the Back2Strong recipe library from Supabase, filter it for a school
// athlete audience, and bake it into index.html between the RECIPES markers.
//
// The app stays a single self-contained file with no runtime dependency on
// Supabase — re-run this script when you want to refresh the library.
//
//   node scripts/pull-recipes.mjs      (key read from .env.local)
//
// Recipes are excluded when they carry a weight-loss or condiment tag: this
// app tells school athletes to fuel properly, and a fat-loss library sitting
// next to that message contradicts it.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

// Key comes from .env.local (gitignored) or the environment — never the repo.
const env = { ...process.env };
if (existsSync('.env.local')) {
  for (const line of readFileSync('.env.local', 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.+?)\s*$/);
    if (m && !env[m[1]]) env[m[1]] = m[2];
  }
}

const URL_BASE = env.SUPABASE_URL || 'https://xlrvcfxgvxfyrmduztza.supabase.co';
const KEY = env.SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_ANON_KEY;
if (!KEY) {
  console.error('No key found. Add SUPABASE_PUBLISHABLE_KEY to .env.local and re-run.');
  process.exit(1);
}

const EXCLUDED_TAGS = ['sauce', 'condiment', 'fat-loss', 'low-carb', 'low-calorie'];

// Which part of the training day a recipe suits. Mirrors the Timing tab.
function phaseFor(r) {
  const carbs = r.carbs_g || 0, protein = r.protein_g || 0;
  if (r.category === 'snack' && carbs < 25) return 'Snack';
  if (protein >= 30 && carbs >= 30) return 'Post-Training';
  if (carbs >= 40) return 'Pre-Training';
  if (['dinner', 'lunch', 'breakfast'].includes(r.category)) return 'Everyday';
  return 'Snack';
}

const res = await fetch(`${URL_BASE}/rest/v1/recipes?published=eq.true&select=*`, {
  headers: { apikey: KEY, Authorization: `Bearer ${KEY}` },
});
if (!res.ok) {
  console.error(`Supabase returned ${res.status}: ${await res.text()}`);
  process.exit(1);
}
const all = await res.json();

const kept = all
  .filter(r => !(r.tags || []).some(t => EXCLUDED_TAGS.includes(t)))
  .map(r => ({
    title: r.title,
    slug: r.slug,
    phase: phaseFor(r),
    category: r.category,
    description: r.description || '',
    servings: r.servings,
    mins: (r.prep_time_mins || 0) + (r.cook_time_mins || 0),
    kcal: r.calories,
    p: r.protein_g,
    c: r.carbs_g,
    f: r.fat_g,
    ingredients: r.ingredients || [],
    method: r.method || [],
    note: r.coach_note || '',
  }))
  .sort((a, b) => a.title.localeCompare(b.title));

const START = '// ── RECIPES (generated by scripts/pull-recipes.mjs — do not edit by hand) ────';
const END = '// ── END RECIPES ─────────────────────────────────────────────────────────────';

const file = 'index.html';
const src = readFileSync(file, 'utf8');
const a = src.indexOf(START), b = src.indexOf(END);
if (a === -1 || b === -1) {
  console.error('RECIPES markers not found in index.html');
  process.exit(1);
}

const body = `${START}\nconst RECIPES = ${JSON.stringify(kept, null, 2)};\n${END}`;
writeFileSync(file, src.slice(0, a) + body + src.slice(b + END.length));

const counts = kept.reduce((m, r) => ({ ...m, [r.phase]: (m[r.phase] || 0) + 1 }), {});
console.log(`${kept.length} of ${all.length} recipes baked in:`, counts);
console.log(`Excluded ${all.length - kept.length} (${EXCLUDED_TAGS.join(', ')})`);
